%% Guideline
% Generate Adp_com.h: message structure define 
% Generate Adp_com.c: define the struct data for ASW 
%                     physical/hex transmission function
% Updata Com_Cbk_Adap.c: fill functions from Adp_com.c 
%
%% dbc handle
if ~(exist('dbcFile','var')==1)
    [dbName,dbPath,filterIndex] = uigetfile('*.dbc','Choose the DBC file');
    dbcFile = [dbPath filesep dbName];
    clear dbName dbPath
end

%if filterIndex ~= 0
db = canDatabase(dbcFile);
tk = 0;
rk = 0;
xk = 0;
lenTxSignal = 0;
lenRxSignal = 0;
lenXxSignal = 0;
clear MSG_Message_Tx;
clear MSG_Message_Rx;
clear MSG_Message_Xx;
clear msgCycles;

attr = db.MessageInfo(1).Attributes;
for i=1:1:length(attr)
    if strcmp(char(attr(i)),'GenMsgCycleTime')
        cycleIdx = i;
    end
end
clear attr

for k = 1:length(db.Messages)
    clear rxdNodes;
    if isempty(db.MessageInfo(k).SignalInfo)
        printf('message %s does not have signals.\n ',db.MessageInfo(k).Name);
    else
        rxdNodes = [];
        for sigCnt = 1:length(db.MessageInfo(k).SignalInfo)
            rxdNodes = [rxdNodes;db.MessageInfo(k).SignalInfo(sigCnt).RxNodes];
        end        
    end
    
    if strcmp(ecuNode,db.MessageInfo(k).TxNodes)    % send messages
        tk = tk + 1;
        MSG_Message_Tx{tk,1} = db.MessageInfo(k).Name;
        MSG_Message_Tx{tk,2} = db.MessageInfo(k).SignalInfo;
        MSG_Message_Tx{tk,3} = length(db.MessageInfo(k).Signals);
        msgCycles(tk) = db.MessageInfo(k).AttributeInfo(cycleIdx).Value;
        lenTxSignal = lenTxSignal + length(db.MessageInfo(k).Signals);
    elseif sum(ismember(ecuNode,rxdNodes))      % receive messages
        rk = rk + 1;
        MSG_Message_Rx{rk,1} = db.MessageInfo(k).Name;
        MSG_Message_Rx{rk,2} = db.MessageInfo(k).SignalInfo;
        MSG_Message_Rx{rk,3} = length(db.MessageInfo(k).Signals);
        lenRxSignal = lenRxSignal + length(db.MessageInfo(k).Signals);
    else
        xk = xk+1;                              % other messages
        MSG_Message_Xx{xk,1} = db.MessageInfo(k).Name;
        MSG_Message_Xx{xk,2} = db.MessageInfo(k).SignalInfo;
        MSG_Message_Xx{xk,3} = length(db.MessageInfo(k).Signals);
        lenXxSignal = lenXxSignal + length(db.MessageInfo(k).Signals);
    end
end

%% creat the Adp_can.h file 
% define the can structure type
hfilehandle = fopen('Adp_can.h','w');

fprintf(hfilehandle,'//%s\n',char(datetime));
fprintf(hfilehandle,'//Generated by %s.m\n',mfilename('fullpath'));
fprintf(hfilehandle,'//May be overwrittern by the matlab generated file\n');
fprintf(hfilehandle, '#ifndef _Adp_CAN_\n#define _Adp_CAN_ (1)\n\n');
fprintf(hfilehandle,'#include "std_type.h"\n');
fprintf(hfilehandle,'\n//message struct definition\n');
for i =1 :tk                                %Message counter
    fprintf(hfilehandle,'typedef struct {\n');
    for j = 1:MSG_Message_Tx{i,3}           % Signale counter
        if MSG_Message_Tx{i,2}(j).SignalSize ==1
            sigType = 'uint8';
        else
            sigType = 'float';
        end
        fprintf(hfilehandle,'    %s %s;\n',sigType,MSG_Message_Tx{i,2}(j).Name);
    end
    fprintf(hfilehandle,'} %s_ST;\n\n',MSG_Message_Tx{i,1});
end

for i =1 :rk                                %Message counter
    fprintf(hfilehandle,'typedef struct {\n');
    for j = 1:MSG_Message_Rx{i,3}           % Signale counter
        if MSG_Message_Rx{i,2}(j).SignalSize ==1
            sigType = 'uint8';
        else
            sigType = 'float';
        end
        fprintf(hfilehandle,'    %s %s;\n',sigType,MSG_Message_Rx{i,2}(j).Name);
    end
    fprintf(hfilehandle,'} %s_ST;\n\n',MSG_Message_Rx{i,1});
end

fprintf(hfilehandle,'typedef struct {\n');
    for i =1 :tk
        fprintf(hfilehandle,'    %s_ST msg_%s;\n',MSG_Message_Tx{i,1},MSG_Message_Tx{i,1});
    end
fprintf(hfilehandle,'} CANTXDST;\n\n');

fprintf(hfilehandle,'typedef struct {\n');
    for i =1 :rk
        fprintf(hfilehandle,'    %s_ST msg_%s;\n',MSG_Message_Rx{i,1},MSG_Message_Rx{i,1});
    end
fprintf(hfilehandle,'} CANRXDST;\n\n');
fprintf(hfilehandle,'#endif\n');
fclose(hfilehandle);
%% creat the Adp_com.h file
% generate the declaration of pack/unpack data
hfilehandle = fopen('Adp_com.h','w');
fprintf(hfilehandle,'//%s\n',char(datetime));
fprintf(hfilehandle,'//Generated by %s.m\n',mfilename('fullpath'));
fprintf(hfilehandle,'//May be overwrittern by the matlab generated file\n');
fprintf(hfilehandle, '#ifndef _Adp_COM_\n#define _Adp_COM_ (1)\n\n');
fprintf(hfilehandle, '#define CANHEADER (1)\n');
fprintf(hfilehandle,'#if CANHEADER\n#include "Adp_can.h"\n#else\n#include "Adp_aswType.h"\n#endif\n');

fprintf(hfilehandle,'\n//message struct definition\n');

fprintf(hfilehandle,'\n//message struct data definition\n');
fprintf(hfilehandle,'extern CANTXDST ComCanTxd;\n');
fprintf(hfilehandle,'extern CANRXDST ComCanRxd;\n');

fprintf(hfilehandle,'\n//callback funtion for pack and unpack data\n');
for i =1 :tk     
    fprintf(hfilehandle, 'extern void set_%s(void);\n',MSG_Message_Tx{i,1});
end

for i =1 :rk     
     fprintf(hfilehandle, 'extern void get_%s(void);\n',MSG_Message_Rx{i,1});
end

idxUsed = zeros(1,length(msgCycles));
for i =1 :tk     
    
    for msgCnt = 1:length(msgCycles)
        cycle = msgCycles(msgCnt);
        if cycle ==0
            idxUsed(msgCnt) = 1;
        end
        
        if idxUsed(msgCnt) == 0
            fprintf(hfilehandle,'extern void Com_packData_%dms(void);\n',cycle);
            for ii = msgCnt:tk
                if cycle == msgCycles(ii)
                    idxUsed(ii) = 1;
                end
            end
        end       
    end
end

for i=1:xk
    msgName = MSG_Message_Xx{i,1};
    fprintf(hfilehandle,'extern void get_%s(void);\n',msgName);  
end
    
fprintf(hfilehandle,'#endif\n');
fclose(hfilehandle);

%% Creat Adp_com.c file 
cfilehandle = fopen('Adp_com.c','w');
fprintf(cfilehandle,'//%s\n',char(datetime));
fprintf(cfilehandle,'//Generated by %s.m\n',mfilename('fullpath'));
fprintf(cfilehandle,'#include "Adp_com.h"\n#include "Com_cfg.h"\n#include "Com.h"\n\n');

fprintf(hfilehandle,'//Global can rxd txd structure\n');
fprintf(hfilehandle,'extern CANTXDST ComCanTxd;\n');
fprintf(hfilehandle,'extern CANRXDST ComCanRxd;\n');
% txd pack data
for i=1:tk
    msgName = MSG_Message_Tx{i,1};
    fprintf(cfilehandle,'\n void set_%s(void)\n{\n',msgName);
    sigCounts = length(MSG_Message_Tx{i,2});
    for sigCnt =  1:sigCounts
        offset = MSG_Message_Tx{i,2}(sigCnt).Offset;
        factor = MSG_Message_Tx{i,2}(sigCnt).Factor;
        sigSize = MSG_Message_Tx{i,2}(sigCnt).SignalSize;
        sigName = MSG_Message_Tx{i,2}(sigCnt).Name;
        if length(sigName)>32
            sigNameLim = sigName(1:32);             %limited by the perl script
        else
            sigNameLim = sigName;
        end
        sigclass =  MSG_Message_Tx{i,2}(sigCnt).Class;
        
        % raw_value = (physical_value - Offset) / Factor
        if factor == 1
            if offset == 0
                fprintf(cfilehandle,'    %s tmp%d = (%s)ComCanTxd.msg_%s.%s ;\n',sigclass,sigCnt,sigclass,msgName,sigName);
            else
                fprintf(cfilehandle,'    %s tmp%d = (%s)(ComCanTxd.msg_%s.%s-(%f)) ;\n',sigclass,sigCnt,sigclass,msgName,sigName,offset);
            end
        else
            if offset == 0
                fprintf(cfilehandle,'    %s tmp%d = (%s)((ComCanTxd.msg_%s.%s)/(%f)) ;\n',sigclass,sigCnt,sigclass,msgName,sigName,factor);    
            else
                fprintf(cfilehandle,'    %s tmp%d = (%s)((ComCanTxd.msg_%s.%s-(%f))/(%f)) ;\n',sigclass,sigCnt,sigclass,msgName,sigName,offset,factor);                        
            end
        end
        
        fprintf(cfilehandle,'    Com_SendSignal(ComSignal_%s, &tmp%d) ;\n',sigNameLim,sigCnt); 
    end
    fprintf(cfilehandle,'}\n');
    
end
% rxd unpack data
for i=1:rk
    msgName = MSG_Message_Rx{i,1};
    fprintf(cfilehandle,'\n void get_%s(void)\n{\n',msgName);
    sigCounts = length(MSG_Message_Rx{i,2});
    for sigCnt =  1:sigCounts
        offset = MSG_Message_Rx{i,2}(sigCnt).Offset;
        factor = MSG_Message_Rx{i,2}(sigCnt).Factor;
        sigSize = MSG_Message_Rx{i,2}(sigCnt).SignalSize;
        sigName = MSG_Message_Rx{i,2}(sigCnt).Name;
        if length(sigName)>32
            sigNameLim = sigName(1:32);             %limited by the perl script
        else
            sigNameLim = sigName;
        end
         sigclass =  MSG_Message_Rx{i,2}(sigCnt).Class;
        if sigSize ==1
            sigType = 'uint8';
        else
            sigType = 'float';
        end
        
        % raw_value = (physical_value - Offset) / Factor
        fprintf(cfilehandle,'    %s tmp%d;\n',sigclass,sigCnt);
        fprintf(cfilehandle,'    Com_ReceiveSignal(ComSignal_%s, &tmp%d) ;\n',sigNameLim,sigCnt);
        if factor == 1
            if offset == 0
                fprintf(cfilehandle,'    ComCanRxd.msg_%s.%s = (%s)(tmp%d) ;\n',msgName,sigName,sigType,sigCnt);
            else
                fprintf(cfilehandle,'    ComCanRxd.msg_%s.%s = (%s)(tmp%d+(%f)) ;\n',msgName,sigName,sigType,sigCnt,offset);
            end
        else
            if offset == 0
                fprintf(cfilehandle,'    ComCanRxd.msg_%s.%s = (%s)(tmp%d*(%f)) ;\n',msgName,sigName,sigType,sigCnt,factor);
            else
                fprintf(cfilehandle,'    ComCanRxd.msg_%s.%s = (%s)(tmp%d*(%f)+(%f)) ;\n',msgName,sigName,sigType,sigCnt,factor,offset);
            end
        end
    end
    fprintf(cfilehandle,'}\n');
end

idxUsed = zeros(1,length(msgCycles));
for i =1 :tk     
    for msgCnt = 1:length(msgCycles)
        cycle = msgCycles(msgCnt);
        if cycle ==0
            idxUsed(msgCnt) = 1;
        end
        if idxUsed(msgCnt) == 0
            fprintf(cfilehandle,' void Com_packData_%dms(void)\n{\n',cycle);
            for ii = msgCnt:tk
                if cycle == msgCycles(ii)
                    idxUsed(ii) = 1;
                    fprintf(cfilehandle,'    set_%s();\n',MSG_Message_Tx{ii,1});
                end
            end
            fprintf(cfilehandle,' }\n\n');
        end
    end
end

for i=1:xk
    msgName = MSG_Message_Xx{i,1};
    fprintf(cfilehandle,'void get_%s(void)\n{\n}\n',msgName);  
end
    
fclose(cfilehandle);

%% Update the cbk
% cbkfilehandle = fopen('Com_Cbk_Adap.c','r+');
% cbkfile = char(fread(cbkfilehandle)');        
% newbkfile = cbkfile;
cbkfile = fileread([mdlRoot '\utilities\ComConf\Com_Cbk_Adap.c']);
cbkfilehandle = fopen('Com_Cbk_Adap.c','w');
%cbkfile = char(fread(cbkfilehandle)');
key1 = 'void ';
key2 = '(void)';
   
keystart = findstr(cbkfile,key1);
keystop = findstr(cbkfile,key2);
%    for i = 2: length(keystop)
%        funend(i-1) = keystart(i);
%    end
%    funend(i) = length(cbkfile);
clear newcbkfile;
newcbkfile = cbkfile;
if (length(keystart) == length(keystop)) &&(~isempty(keystart))
    for funCnt = 1:length(keystart)     
        tmpfindkey1 = findstr(newcbkfile,key1);
        tmpfindkey2 = findstr(newcbkfile,key2);
        funStart = tmpfindkey1(funCnt);       % void postion
        funMid  =  tmpfindkey2(funCnt);       %first ( position
        if funCnt == length(keystart)
            funEnd = length(newcbkfile);
        else
          funEnd = tmpfindkey1(funCnt+1);   % Last } position
        end
              
        funDef = newcbkfile(funStart+length(key1):funMid-1);
        if startsWith(funDef,'Com_RxCbk')
            funCbk = ['    ',replace(funDef,'Com_RxCbk','get'),'();',newline];
        elseif startsWith(funDef,'Com_TxCbk')
            funCbk = ['    ',replace(funDef,'Com_TxCbk','set'),'();',newline];
        else
            funCbk = [];
        end
        % fill the funCbk into the positioned {}
        % only one pair {} in the function 

        firstBracket = funStart + min(findstr(newcbkfile(funStart:funEnd),'{'));
        lastBracket = funStart + max(findstr(newcbkfile(funStart:funEnd),'}'))-1;

        newcbkfile = [newcbkfile(1:firstBracket),...
                        funCbk,...
                        newcbkfile(lastBracket:length(newcbkfile)) ];               
       end
   end
   % insert #include "Adp_can.h" 
   includepos = min(findstr(newcbkfile,'#include'));
   insertData = ['#include "Adp_com.h"', newline()];
   if isempty(strfind(newcbkfile,insertData))
        if includepos==1
             insertBefore = [];
            insertAfter = newcbkfile;
        else
            insertBefore = newcbkfile(1:includepos-1);
            insertAfter = newcbkfile(includepos: length(newcbkfile));
        end
        newcbkfile= [insertBefore, insertData, insertAfter];
   end
   fprintf(cbkfilehandle,'//%s    :',char(datetime));
   fprintf(cbkfilehandle,'//Updated by %s.m\n',mfilename('fullpath'));
   fprintf(cbkfilehandle,'%s',newcbkfile);
   fclose(cbkfilehandle);   
%end
%% clear
clear db
clear cbkfile cbkfilename newcbkfile
clear cfilehandle hfilehandle cbkfilehandle
clear i j k
clear tk rk cycleIdx xk
clear keystart keystop lenRxSignal lenTxSignal
clear funStart funMid funEnd funCbk funCnt funDef
clear key1 key2 firstBracket lastBracket
clear sigCnt sigCounts sigName sigNameLim sigSize sigType sigclass
clear tmpfindkey1 tmpfindkey2
clear offset factor msgName rxdNodes MSG_Message_Rx MSG_Message_Tx MSG_Message_Xx
clear insertData insertAfter insertBefore includepos 
clear lenXxSignal ii idxUsed cycle msgCnt msgCycles 

