
%% get the port information
portFile = 'canPort.ini';
portFileHdl = fopen(portFile);
tline = fgetl(portFileHdl);  %line 1
portDef = [];
for i = 1:4             %line 2~5
    tline = fgetl(portFileHdl);
    portDef{i} = textscan(tline,'%s %s %s %s');
end
fclose(portFileHdl);
%% update Can_NodeType_ten_0 in can_cfg.h hfile
% Can_NodeType_ten_0
idxNodeName=1;
idxNodeId=2;
idxTxd=3;
idxRxd=4;
nodeDef=[];
for i =1:4
    if ~isempty(portDef{i}{idxNodeId})
        nodeDef = [nodeDef sprintf('    %s_CAN_0 = %s,\n',char(portDef{i}{idxNodeName}),char(portDef{i}{idxNodeId}))];
    end
end

nodeDef = nodeDef(1:length(nodeDef)-2);

hfile = 'Can_Cfg.h';
hfileTxt = fileread(hfile);

pos = findstr(hfileTxt,'Can_NodeType_ten_0');
firstBracket = max(findstr(hfileTxt(1:pos),'{'));
lastBracket =  max(findstr(hfileTxt(1:pos),'}'));
hfileTxt = [ hfileTxt(1:firstBracket),...
                newline,nodeDef,newline,...
               hfileTxt(lastBracket: length(hfileTxt)) ];
hfileHdl = fopen(hfile,'w');
fprintf(hfileHdl,'%s',hfileTxt);
fclose(hfileHdl);
clear hfileTxt

%%moved

%% creat init_can_port in init_can_port.c  
fileName = 'init_mcan_port.c';
fileHdl = fopen(fileName,'w');
fprintf(fileHdl,'//%s\n//Generated by %s.m\n',char(datetime),mfilename('fullpath'));
fprintf(fileHdl,'#include "pinmapper/aurix_pin_mappings.h"\n');
fprintf(fileHdl,'#include "_PinMap/IfxMultiCAN_PinMap.h"\n');
fprintf(fileHdl,'#include "MultiCAN/Std/IfxMultican.h"\n'); 
fprintf(fileHdl,'\n');

fprintf(fileHdl,'void init_mcan_port(void)\n{\n');
for i=1:4
   hwNode = i;
%        hwNode = str2num(char(portDef{i}{idxNodeId}));
%        hwTxd = portDef{i}{idxTxd};
%        hwRxd = (portDef{i}{idxRxd});
%        if ~(isempty(hwTxd) || isempty(hwRxd))
   fprintf(fileHdl,'#ifdef IFXCFG_MULTICAN0_%d_TXD\n',hwNode);
   fprintf(fileHdl,'    IfxPort_setPinModeOutput( IFXCFG_MULTICAN0_%d_TXD.pin.port,\n',hwNode);
   fprintf(fileHdl,'                              IFXCFG_MULTICAN0_%d_TXD.pin.pinIndex,\n',hwNode);
   fprintf(fileHdl,'                              IFXCFG_MULTICAN0_%d_TXD_MODE,\n',hwNode);
   fprintf(fileHdl,'                              IFXCFG_MULTICAN0_%d_TXD.select\n',hwNode);
   fprintf(fileHdl,'                             );\n');

   fprintf(fileHdl,'    IfxPort_setPinPadDriver(  IFXCFG_MULTICAN0_%d_TXD.pin.port,\n',hwNode);
   fprintf(fileHdl,'                              IFXCFG_MULTICAN0_%d_TXD.pin.pinIndex,\n',hwNode);
   fprintf(fileHdl,'                              IFXCFG_MULTICAN0_%d_TXD_PAD_DRIVER\n',hwNode);
   fprintf(fileHdl,'                             );\n#endif\n\n');

   fprintf(fileHdl,'#ifdef IFXCFG_MULTICAN0_%d_RXD\n',hwNode);
   fprintf(fileHdl,'    IfxPort_setPinModeInput(  IFXCFG_MULTICAN0_%d_RXD.pin.port,\n',hwNode);
   fprintf(fileHdl,'                              IFXCFG_MULTICAN0_%d_RXD.pin.pinIndex,\n',hwNode);
   fprintf(fileHdl,'                              IFXCFG_MULTICAN0_%d_RXD_MODE\n',hwNode);
   fprintf(fileHdl,'                             );\n#endif\n\n');
end
   
fprintf(fileHdl,'}\n');
fclose(fileHdl);
 

%% clear
clear pinSel pos u idxRxd idxTxd hwRxd hwTxd idxNodeId idxNodeName
clear lastBracket pinSelected portFile portFileHdl rxSel tline i
