%% Guideline
% define the enumeration types for both asw and bsw using the direct valued
% integer.
% ECM: Enumerated Control Mode
% EGM: Enumerated Gate Mode
% ESM: Enumerated System Mode
% TQL: TorQue Limit status
% TST: sw self-TeST status
% EIS: Enumerated Is(stator current) control mode

%% Create enumerated types and define simulink enumeration signals

% template
% Simulink.defineIntEnumType('BasicColors', ... 
% 	{'Red', 'Yellow', 'Blue'}, ...
% 	[0;1;2], ... 
% 	'Description', 'Basic colors', ...
% 	'DefaultValue', 'Blue', ...
% 	'HeaderFile', 'mybasiccolors.h', ...
% 	'DataScope', 'Exported', ...
% 	'AddClassNameToEnumNames', true, ...
% 	'StorageType', 'int16');

if exist('ECM','class')~=9
    Simulink.defineIntEnumType('ECM',...
        {'Init','nCtrl','TrqCtrl','IsCtrl','UdcCtrl','DCYCtrl','alOfsCal','IFCtrl','Discharge','OC'},...
        [0,1,2,3,4,5,6,7,8,9],...
        'DataScope','Exported');
end

if exist('EGM','class')~=8
    Simulink.defineIntEnumType('EGM',...
        {'Freewheel','Shortcircuit','ShortcircuitTop','PWMRun','PWMDischarge'},...
        [0,1,2,3,4],...
        'DataScope','Exported');
end

if exist('ESM','class')~=8
    Simulink.defineIntEnumType('ESM',...
        {'PreDrive','Drive','PostDrive'},...
        [0,1,2],...
        'DataScope','Exported');
end

if exist('EiceSilOPM','class')~=8
    Simulink.defineIntEnumType('EiceSilOPM',...
        {'OPM0','OPM1','OPM2','OPM3','OPM4','OPM5','OPM6'},...
        [0,1,2,3,4,5,6],...
        'DataScope','Exported');
end

if exist('EiceSilSM','class')~=8
    Simulink.defineIntEnumType('EiceSilSM',...
        {'EsNotOk','EsInin','EsClrErrHist','EsLvMoCSOP','EsHvMoCSOP','EsTarMod3','EsTarMod5','EsReadSts','EsOk','EsErr','EsRxParErr','EsSpiHwUnitErr'},...
        [0,1,2,3,4,5,6,7,8,9,10,11],...
        'DataScope','Exported');
end

if exist('TQL','class')~=8
    Simulink.defineIntEnumType('TQL',...
        {'Inactive','OpRngElmMot','OpRngElmGen','TStrMax','TRtrMax','TIGBTMAX','IdcMax','IdcMin','UdcMax','UdcMin','nLim','DIATrqMax','DIATrqMin','DIAPwrMax','DIAPwrMin','CANMax','CANMin','Error','ImbLim','TCoolObsMax'},...
        [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19],...
        'DataScope','Exported');
end

if exist('TST','class')~=8
    Simulink.defineIntEnumType('TST',...
        {'NotTest','TestOK','errHigh','errLow'},...
        [0,1,2,3],...
        'DataScope','Exported');
end

if exist('EIS','class')~=8
    Simulink.defineIntEnumType('EIS',...
        {'Calc','IdIq','IsPhi','IsCtl'},...
        [0,1,2,3],...
        'DataScope','Exported');
end


%% clear









